{{- if and (not .Values.ontapConfig.existingSecret) (not .Values.externalSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ontap-mcp.configSecretName" . }}
  labels:
    {{- include "ontap-mcp.labels" . | nindent 4 }}
type: Opaque
data:
  ontap.yaml: {{ toYaml .Values.ontapConfig.data | b64enc | quote }}
{{- end }}
